name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.24]
        service: [user-service-todo, task-service-todo, notes-service-todo, email-service-todo, auth-service-todo]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Build ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          mkdir -p bin
          go build -o bin/${{ matrix.service }} ./cmd/main.go

      - name: Test ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          go test ./...